### ISSUE TITLE
Proper citation of bachelor and master thesis

### ISSUE THREAD

**Issue by krusche** [ls1intum/thesis-template-typst#82]
I saw many cases where students to not cite other bachelor and master theses correctly. Most leave out the type and the university in the bibliography, which makes it unclear what kind of document it is.

Preferable we implement support for [yml based citations ](https://github.com/typst/hayagriva/blob/main/docs/file-format.md)and add an example such as 

```
kutsch2023localci:
  type: thesis
  title: "Local Continuous Integration in Artemis"
  author: Frederik Kutsch
  genre: Master Thesis 
  publisher: Technical University of Munich
  date: 2023
```
